#!/usr/bin/env node
'use strict';
/**
 * Verifies that pages/calc.js produces results identical to calc.py (within
 * floating-point tolerance) for a set of reference inputs generated by
 * tests/gen_calc_reference.py.
 *
 * Usage: node tests/test_calc_parity.js <path-to-reference.json>
 */

const fs   = require('fs');
const path = require('path');

const calc = require(path.join(__dirname, '..', 'pages', 'calc.js'));

const refPath = process.argv[2];
if (!refPath) {
    console.error('Usage: node test_calc_parity.js <reference.json>');
    process.exit(1);
}
const reference = JSON.parse(fs.readFileSync(refPath, 'utf8'));

// Both implementations use IEEE 754 doubles and the same formula, so
// results should agree to near machine epsilon. 1e-9 is generous.
const REL_TOL = 1e-9;
let failures  = 0;

function check(label, got, expected) {
    const err = expected !== 0
        ? Math.abs(got - expected) / Math.abs(expected)
        : Math.abs(got);
    if (err > REL_TOL) {
        console.error(`FAIL  ${label}`);
        console.error(`      expected  ${expected}`);
        console.error(`      got       ${got}`);
        console.error(`      rel error ${err.toExponential(3)}`);
        failures++;
    }
}

for (const ref of reference) {
    const { t, rh, p_hpa } = ref;
    const p   = p_hpa * 100.0;
    const x   = calc.mixing_ratio(t, rh, p);
    const tag = `T=${t} RH=${rh} p=${p_hpa}`;

    check(`${tag}: mixing_ratio`,      x,                             ref.mixing_ratio);
    check(`${tag}: absolute_humidity`, calc.absolute_humidity(t, rh), ref.absolute_humidity);
    check(`${tag}: heat_index`,        calc.heat_index(t, x, p),      ref.heat_index);
    check(`${tag}: d_hi_d_t`,          calc.d_hi_d_t(t, x, p),       ref.d_hi_d_t);
    check(`${tag}: d_hi_d_x`,          calc.d_hi_d_x(t, x, p),       ref.d_hi_d_x);
}

if (failures > 0) {
    console.error(`\n${failures} check(s) failed.`);
    process.exit(1);
}
console.log(`OK — ${reference.length} cases × 5 values, all within rel=${REL_TOL}`);
